language: python
python:
- '2.7'
- '3.3'
- '3.4'
- pypy
script:
- env
- deactivate
- python --version
- source environment
notifications:
  email: false
env:
  global:
    secure: q8M16jIP5uoo9A+KFiKzPSzsHvO0SMey55upbd1v5YG3aNS3lN7Ix8qtPHbtev6uE7tW94Tn0tkIiMdVUhgfylC+nSwBAfNqEznZxq+FE3lBYnkHz5QPwEWe3DD3d8QrpknKZjc2jDWxDDELFotL5Ey7n9vSCdiE2HBQZFe7S60=
